---
version: '3'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: 172.21.0.11:2888:3888
    networks:
      laboratorio:
        ipv4_address: 172.21.0.11
    ports:
      - "2181:2181"
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-1:
    image: confluentinc/cp-enterprise-kafka:latest
    networks:
      laboratorio:
        ipv4_address: 172.21.0.21
    depends_on:
      - zookeeper-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: '172.21.0.11:2181/kafka'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://172.21.0.21:9092'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: 172.21.0.21:9092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: '172.21.0.11:2181/kafka'
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    extra_hosts:
      - "moby:127.0.0.1"

  schema_registry-1:
    image: confluentinc/cp-schema-registry
    networks:
      laboratorio:
        ipv4_address: 172.21.0.31
    hostname: schema_registry
    depends_on:
      - zookeeper-1
      - kafka-1
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: '172.21.0.11:2181/kafka'
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 1

  control-center-1:
    image: confluentinc/cp-enterprise-control-center:4.0.0
    ports:
      - "9021:9021"
    networks:
      laboratorio:
        ipv4_address: 172.21.0.51
    depends_on:
      - zookeeper-1
      - kafka-1
      - schema_registry-1
    environment:
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 172.21.0.11:2181/control-center
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 172.21.0.21:9092
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 3
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 3
      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 2
      CONTROL_CENTER_CONNECT_CLUSTER: http://172.21.0.41:8083
    extra_hosts:
      - "moby:127.0.0.1"

networks:
    laboratorio:
        driver: bridge
        ipam:
          config:
            - subnet: 172.21.0.0/24
